/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category AddDelegateAddress
 * @category generated
 */
export type AddDelegateAddressInstructionArgs = {
  address: web3.PublicKey
}
/**
 * @category Instructions
 * @category AddDelegateAddress
 * @category generated
 */
export const addDelegateAddressStruct = new beet.BeetArgsStruct<
  AddDelegateAddressInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['address', beetSolana.publicKey],
  ],
  'AddDelegateAddressInstructionArgs'
)
/**
 * Accounts required by the _addDelegateAddress_ instruction
 *
 * @property [_writable_] delegateAccount
 * @property [_writable_, **signer**] signer
 * @property [_writable_] treasury
 * @category Instructions
 * @category AddDelegateAddress
 * @category generated
 */
export type AddDelegateAddressInstructionAccounts = {
  delegateAccount: web3.PublicKey
  signer: web3.PublicKey
  treasury: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addDelegateAddressInstructionDiscriminator = [
  21, 143, 207, 169, 27, 95, 219, 198,
]

/**
 * Creates a _AddDelegateAddress_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddDelegateAddress
 * @category generated
 */
export function createAddDelegateAddressInstruction(
  accounts: AddDelegateAddressInstructionAccounts,
  args: AddDelegateAddressInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = addDelegateAddressStruct.serialize({
    instructionDiscriminator: addDelegateAddressInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.delegateAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
