/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category AddOwner
 * @category generated
 */
export type AddOwnerInstructionArgs = {
  owner: web3.PublicKey
}
/**
 * @category Instructions
 * @category AddOwner
 * @category generated
 */
export const addOwnerStruct = new beet.BeetArgsStruct<
  AddOwnerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['owner', beetSolana.publicKey],
  ],
  'AddOwnerInstructionArgs'
)
/**
 * Accounts required by the _addOwner_ instruction
 *
 * @property [_writable_] votebank
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category AddOwner
 * @category generated
 */
export type AddOwnerInstructionAccounts = {
  votebank: web3.PublicKey
  signer: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addOwnerInstructionDiscriminator = [
  211, 140, 15, 161, 64, 48, 232, 184,
]

/**
 * Creates a _AddOwner_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddOwner
 * @category generated
 */
export function createAddOwnerInstruction(
  accounts: AddOwnerInstructionAccounts,
  args: AddOwnerInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = addOwnerStruct.serialize({
    instructionDiscriminator: addOwnerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.votebank,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
