/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export type CancelProposalInstructionArgs = {
  proposalId: number
}
/**
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export const cancelProposalStruct = new beet.BeetArgsStruct<
  CancelProposalInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['proposalId', beet.u32],
  ],
  'CancelProposalInstructionArgs'
)
/**
 * Accounts required by the _cancelProposal_ instruction
 *
 * @property [_writable_] proposal
 * @property [_writable_] votebank
 * @property [_writable_, **signer**] proposalOwner
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export type CancelProposalInstructionAccounts = {
  proposal: web3.PublicKey
  votebank: web3.PublicKey
  proposalOwner: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const cancelProposalInstructionDiscriminator = [
  106, 74, 128, 146, 19, 65, 39, 23,
]

/**
 * Creates a _CancelProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export function createCancelProposalInstruction(
  accounts: CancelProposalInstructionAccounts,
  args: CancelProposalInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = cancelProposalStruct.serialize({
    instructionDiscriminator: cancelProposalInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.votebank,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalOwner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
