/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitializeFeePayer
 * @category generated
 */
export type InitializeFeePayerInstructionArgs = {
  lamports: beet.bignum
}
/**
 * @category Instructions
 * @category InitializeFeePayer
 * @category generated
 */
export const initializeFeePayerStruct = new beet.BeetArgsStruct<
  InitializeFeePayerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['lamports', beet.u64],
  ],
  'InitializeFeePayerInstructionArgs'
)
/**
 * Accounts required by the _initializeFeePayer_ instruction
 *
 * @property [_writable_] feePayer
 * @property [_writable_, **signer**] signer
 * @property [] votebank
 * @category Instructions
 * @category InitializeFeePayer
 * @category generated
 */
export type InitializeFeePayerInstructionAccounts = {
  feePayer: web3.PublicKey
  signer: web3.PublicKey
  votebank: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initializeFeePayerInstructionDiscriminator = [
  84, 243, 98, 42, 236, 238, 134, 30,
]

/**
 * Creates a _InitializeFeePayer_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeFeePayer
 * @category generated
 */
export function createInitializeFeePayerInstruction(
  accounts: InitializeFeePayerInstructionAccounts,
  args: InitializeFeePayerInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = initializeFeePayerStruct.serialize({
    instructionDiscriminator: initializeFeePayerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.feePayer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.votebank,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
