/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category RemoveOwner
 * @category generated
 */
export type RemoveOwnerInstructionArgs = {
  owner: web3.PublicKey
}
/**
 * @category Instructions
 * @category RemoveOwner
 * @category generated
 */
export const removeOwnerStruct = new beet.BeetArgsStruct<
  RemoveOwnerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['owner', beetSolana.publicKey],
  ],
  'RemoveOwnerInstructionArgs'
)
/**
 * Accounts required by the _removeOwner_ instruction
 *
 * @property [_writable_] votebank
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category RemoveOwner
 * @category generated
 */
export type RemoveOwnerInstructionAccounts = {
  votebank: web3.PublicKey
  signer: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const removeOwnerInstructionDiscriminator = [
  153, 251, 84, 208, 33, 62, 15, 247,
]

/**
 * Creates a _RemoveOwner_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveOwner
 * @category generated
 */
export function createRemoveOwnerInstruction(
  accounts: RemoveOwnerInstructionAccounts,
  args: RemoveOwnerInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = removeOwnerStruct.serialize({
    instructionDiscriminator: removeOwnerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.votebank,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
