/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * @category Instructions
 * @category RemoveDelegateAddress
 * @category generated
 */
export type RemoveDelegateAddressInstructionArgs = {
  address: web3.PublicKey
}
/**
 * @category Instructions
 * @category RemoveDelegateAddress
 * @category generated
 */
export const removeDelegateAddressStruct = new beet.BeetArgsStruct<
  RemoveDelegateAddressInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['address', beetSolana.publicKey],
  ],
  'RemoveDelegateAddressInstructionArgs'
)
/**
 * Accounts required by the _removeDelegateAddress_ instruction
 *
 * @property [_writable_] delegateAccount
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category RemoveDelegateAddress
 * @category generated
 */
export type RemoveDelegateAddressInstructionAccounts = {
  delegateAccount: web3.PublicKey
  signer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const removeDelegateAddressInstructionDiscriminator = [
  132, 44, 151, 203, 142, 113, 136, 40,
]

/**
 * Creates a _RemoveDelegateAddress_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveDelegateAddress
 * @category generated
 */
export function createRemoveDelegateAddressInstruction(
  accounts: RemoveDelegateAddressInstructionAccounts,
  args: RemoveDelegateAddressInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = removeDelegateAddressStruct.serialize({
    instructionDiscriminator: removeDelegateAddressInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.delegateAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
