/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category SignDelegateAddress
 * @category generated
 */
export const signDelegateAddressStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'SignDelegateAddressInstructionArgs'
)
/**
 * Accounts required by the _signDelegateAddress_ instruction
 *
 * @property [_writable_] delegateAccount
 * @property [_writable_, **signer**] signer
 * @category Instructions
 * @category SignDelegateAddress
 * @category generated
 */
export type SignDelegateAddressInstructionAccounts = {
  delegateAccount: web3.PublicKey
  signer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const signDelegateAddressInstructionDiscriminator = [
  137, 86, 111, 154, 83, 100, 241, 192,
]

/**
 * Creates a _SignDelegateAddress_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category SignDelegateAddress
 * @category generated
 */
export function createSignDelegateAddressInstruction(
  accounts: SignDelegateAddressInstructionAccounts,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = signDelegateAddressStruct.serialize({
    instructionDiscriminator: signDelegateAddressInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.delegateAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
