/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WithdrawLamports
 * @category generated
 */
export type WithdrawLamportsInstructionArgs = {
  returnLamports: beet.bignum
}
/**
 * @category Instructions
 * @category WithdrawLamports
 * @category generated
 */
export const withdrawLamportsStruct = new beet.BeetArgsStruct<
  WithdrawLamportsInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['returnLamports', beet.u64],
  ],
  'WithdrawLamportsInstructionArgs'
)
/**
 * Accounts required by the _withdrawLamports_ instruction
 *
 * @property [_writable_] treasury
 * @property [_writable_] feePayer
 * @property [] votebank
 * @category Instructions
 * @category WithdrawLamports
 * @category generated
 */
export type WithdrawLamportsInstructionAccounts = {
  treasury: web3.PublicKey
  feePayer: web3.PublicKey
  votebank: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const withdrawLamportsInstructionDiscriminator = [
  251, 144, 115, 229, 113, 247, 206, 64,
]

/**
 * Creates a _WithdrawLamports_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category WithdrawLamports
 * @category generated
 */
export function createWithdrawLamportsInstruction(
  accounts: WithdrawLamportsInstructionAccounts,
  args: WithdrawLamportsInstructionArgs,
  programId = new web3.PublicKey('mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1')
) {
  const [data] = withdrawLamportsStruct.serialize({
    instructionDiscriminator: withdrawLamportsInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feePayer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.votebank,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
