/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */
import type * as web3 from '@solana/web3.js';
import * as beet from '@metaplex-foundation/beet';
import * as beetSolana from '@metaplex-foundation/beet-solana';
export type QuantifiedMint = {
	mint: web3.PublicKey;
	amount: beet.bignum;
};

/**
 * @category userTypes
 * @category generated
 */
export const quantifiedMintBeet = new beet.BeetArgsStruct<QuantifiedMint>(
	[
		['mint', beetSolana.publicKey],
		['amount', beet.u64]
	],
	'QuantifiedMint'
);
