/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type VoteOption = {
  id: number
  title: string
  voteCount: number
}

/**
 * @category userTypes
 * @category generated
 */
export const voteOptionBeet = new beet.FixableBeetArgsStruct<VoteOption>(
  [
    ['id', beet.u8],
    ['title', beet.utf8String],
    ['voteCount', beet.u32],
  ],
  'VoteOption'
)
