/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
import { DelegateAddress, delegateAddressBeet } from '../types/DelegateAddress'

/**
 * Arguments used to create {@link DelegateAccount}
 * @category Accounts
 * @category generated
 */
export type DelegateAccountArgs = {
  delegateOwner: web3.PublicKey
  accounts: DelegateAddress[]
}

export const delegateAccountDiscriminator = [
  218, 249, 88, 50, 225, 236, 46, 241,
]
/**
 * Holds the data for the {@link DelegateAccount} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class DelegateAccount implements DelegateAccountArgs {
  private constructor(
    readonly delegateOwner: web3.PublicKey,
    readonly accounts: DelegateAddress[]
  ) {}

  /**
   * Creates a {@link DelegateAccount} instance from the provided args.
   */
  static fromArgs(args: DelegateAccountArgs) {
    return new DelegateAccount(args.delegateOwner, args.accounts)
  }

  /**
   * Deserializes the {@link DelegateAccount} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [DelegateAccount, number] {
    return DelegateAccount.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link DelegateAccount} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<DelegateAccount> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find DelegateAccount account at ${address}`)
    }
    return DelegateAccount.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, delegateAccountBeet)
  }

  /**
   * Deserializes the {@link DelegateAccount} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [DelegateAccount, number] {
    return delegateAccountBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link DelegateAccount} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return delegateAccountBeet.serialize({
      accountDiscriminator: delegateAccountDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link DelegateAccount} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: DelegateAccountArgs) {
    const instance = DelegateAccount.fromArgs(args)
    return delegateAccountBeet.toFixedFromValue({
      accountDiscriminator: delegateAccountDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link DelegateAccount} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: DelegateAccountArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      DelegateAccount.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link DelegateAccount} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      delegateOwner: this.delegateOwner.toBase58(),
      accounts: this.accounts,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const delegateAccountBeet = new beet.FixableBeetStruct<
  DelegateAccount,
  DelegateAccountArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['delegateOwner', beetSolana.publicKey],
    ['accounts', beet.array(delegateAddressBeet)],
  ],
  DelegateAccount.fromArgs,
  'DelegateAccount'
)
