/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link FeePayer}
 * @category Accounts
 * @category generated
 */
export type FeePayerArgs = {
  isInitialized: boolean
}

export const feePayerDiscriminator = [3, 252, 50, 162, 76, 46, 144, 213]
/**
 * Holds the data for the {@link FeePayer} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class FeePayer implements FeePayerArgs {
  private constructor(readonly isInitialized: boolean) {}

  /**
   * Creates a {@link FeePayer} instance from the provided args.
   */
  static fromArgs(args: FeePayerArgs) {
    return new FeePayer(args.isInitialized)
  }

  /**
   * Deserializes the {@link FeePayer} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [FeePayer, number] {
    return FeePayer.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link FeePayer} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<FeePayer> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find FeePayer account at ${address}`)
    }
    return FeePayer.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'mdVo394XANGMrVXZCVAaX3AMHYvtTxXwg1sQmDSY1W1'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, feePayerBeet)
  }

  /**
   * Deserializes the {@link FeePayer} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [FeePayer, number] {
    return feePayerBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link FeePayer} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return feePayerBeet.serialize({
      accountDiscriminator: feePayerDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link FeePayer}
   */
  static get byteSize() {
    return feePayerBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link FeePayer} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      FeePayer.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link FeePayer} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === FeePayer.byteSize
  }

  /**
   * Returns a readable version of {@link FeePayer} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      isInitialized: this.isInitialized,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const feePayerBeet = new beet.BeetStruct<
  FeePayer,
  FeePayerArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['isInitialized', beet.bool],
  ],
  FeePayer.fromArgs,
  'FeePayer'
)
